<?php

namespace App\Http\Controllers;

use App\DockerfileHelpers\DockerfileDbMsSql;
use App\DockerfileHelpers\DockerfileDbMySql;
use App\DockerfileHelpers\DockerfileDbOraSql;
use App\DockerfileHelpers\DockerfileDbPgSql;
use App\DockerfileHelpers\DockerfileDbSqlite;
use App\DockerfileHelpers\DockerfileFileSize;
use App\DockerfileHelpers\DockerfileGeneralHelpers;
use App\DockerfileHelpers\DockerfileOsModules;
use App\DockerfileHelpers\DockerfilePhpExtensions;
use App\DockerfileHelpers\DockerfileTimeout;
use Illuminate\Http\Request;

class DockerImageBuilderController extends Controller
{
    public function index(Request $request)
    {
        $data = (object) $request->json()->all();
        $plan = json_decode(json_encode($data));
        $image = $plan->image ?? (object) [];
        // Set defaults in the image object
        $image->name = $image->name ?? 'php';
        $phpVersion = $plan->build->php ?? '8.4';
        if ($image->name === 'php') {
            $image->tag = "{$phpVersion}-latest-slim";
        } else {
            // Use the tag from the plan if provided, otherwise default to 'latest'
            $image->tag = $image->tag ?? 'latest';
        }
        $image->databases = $image->databases ?? [];
        $image->os_modules = $image->os_modules ?? [];
        $image->php_extensions = $image->php_extensions ?? [];
        $isUbuntu = str_contains($image->name, 'ubuntu');
        $phpVersion = DockerfileGeneralHelpers::getPhpVersion($image->tag);
        $iniFileLocation = DockerfileGeneralHelpers::getPhpIniLocation($image->tag);
        $dockerfile = $this->buildDockerfile(
            $plan,
            $image,
            $phpVersion,
            $iniFileLocation,
            $isUbuntu
        );

        return response($dockerfile, 200)->header('Content-Type', 'text/yaml');
    }

    // ---------------------------------------------------------------------
    private function buildDockerfile(
        object $plan,
        object $image,
        string $phpVersion,
        string $iniFileLocation,
        bool $isUbuntu
    ): string {
        $dockerfile = $this->getHeader();
        $dockerfile .= $this->buildBuilderStage($image, $phpVersion);
        $dockerfile .= "\n# -----------------------------\n# Runtime Stage\n# -----------------------------\n";
        $dockerfile .= "FROM uadevelopment/{$image->name}:{$image->tag}\n\n";
        $dockerfile .= "ENV SESSION_SECURE_COOKIE=true\n\n";
        $dockerfile .= $this->getCopyCommands($image, $phpVersion);
        $dockerfile .= "USER root\n\n";
        $dockerfile .= $this->buildConsolidatedRunCommand(
            $plan,
            $phpVersion,
            $iniFileLocation,
            $image,
            $isUbuntu
        );
        $dockerfile .= "\nUSER webuser\n";

        return $dockerfile;
    }

    // ---------------------------------------------------------------------
    private function getHeader(): string
    {
        return "#***********************************************\n"
             ."#* This is an autogenerated dev Dockerfile\n"
             ."#* Do not edit this file directly — edit deploy-plan.json\n"
             ."#* and re-run the generator.\n"
             ."#***********************************************\n\n";
    }

    // ---------------------------------------------------------------------
    private function buildBuilderStage(object $image, string $phpVersion): string
    {
        $builder = "# -------- Builder Stage --------\n"
                 ."FROM uadevelopment/{$image->name}:{$image->tag} AS builder\n\n"
                 ."USER root\n\n";

        if (in_array('oracle', $image->databases, false)) {
            $builder .= DockerfileDbOraSql::getBuilderAdditions($phpVersion);
        }
        if (in_array('mssql', $image->databases, false)) {
            $builder .= DockerfileDbMsSql::getBuilderAdditions($phpVersion);
        }
        if (in_array('mysql', $image->databases, false)) {
            $builder .= DockerfileDbMySql::getBuilderAdditions();
        }
        if (in_array('pgsql', $image->databases, false)) {
            $builder .= DockerfileDbPgSql::getBuilderAdditions();
        }
        if (in_array('sqlite', $image->databases, false)) {
            $builder .= DockerfileDbSqlite::getBuilderAdditions();
        }
        if (count($image->php_extensions) > 0) {
            $separated = DockerfilePhpExtensions::separateExtensions($image->php_extensions);
            if (count($separated['pickle']) > 0) {
                $builder .= DockerfilePhpExtensions::getBuilderAdditions($phpVersion, $separated['pickle']);
            }
        }

        return $builder."\n";
    }

    // ---------------------------------------------------------------------
    private function getCopyCommands(object $image, string $phpVersion): string
    {
        $copies = "# Copy compiled artifacts from builder stage\n";

        if (in_array('oracle', $image->databases, false)) {
            $copies .= rtrim(DockerfileDbOraSql::getCopyCommands($phpVersion))."\n";
        }
        if (in_array('mssql', $image->databases, false)) {
            $copies .= rtrim(DockerfileDbMsSql::getCopyCommands($phpVersion))."\n";
        }
        if (in_array('mysql', $image->databases, false)) {
            $copies .= rtrim(DockerfileDbMySql::getCopyCommands($phpVersion))."\n";
        }
        if (in_array('pgsql', $image->databases, false)) {
            $copies .= rtrim(DockerfileDbPgSql::getCopyCommands($phpVersion))."\n";
        }
        if (in_array('sqlite', $image->databases, false)) {
            $copies .= rtrim(DockerfileDbSqlite::getCopyCommands($phpVersion))."\n";
        }
        if (count($image->php_extensions) > 0) {
            $separated = DockerfilePhpExtensions::separateExtensions($image->php_extensions);
            if (count($separated['pickle']) > 0) {
                $copies .= rtrim(DockerfilePhpExtensions::getCopyCommands($phpVersion, $separated['pickle'])) . "\n";
            }
        }

        // Application files
        $copies .= "COPY --chown=webuser app /var/www/html/app\n";
        $copies .= "COPY --chown=webuser bootstrap /var/www/html/bootstrap\n";
        $copies .= "COPY --chown=webuser config /var/www/html/config\n";
        $copies .= "COPY --chown=webuser public /var/www/html/public\n";
        $copies .= "COPY --chown=webuser resources /var/www/html/resources\n";
        $copies .= "COPY --chown=webuser routes /var/www/html/routes\n";
        $copies .= "COPY --chown=webuser storage /var/www/html/storage\n";
        $copies .= "COPY --chown=webuser vendor /var/www/html/vendor\n";
        $copies .= "COPY --chown=webuser database /var/www/html/database\n";
        $copies .= "COPY --chown=webuser artisan /var/www/html/artisan\n";
        $copies .= "COPY --chown=webuser composer.json /var/www/html/composer.json\n";

        return $copies."\n";
    }

    // ---------------------------------------------------------------------
    private function buildConsolidatedRunCommand(
        object $plan,
        string $phpVersion,
        string $iniFileLocation,
        object $image,
        bool $isUbuntu
    ): string {
        $commands = [];

        // ---------------- Minimal runtime packages ----------------
        $packages = ['nodejs', 'npm'];
        $commands[] = 'apk add --no-cache ' . implode(' ', $packages);

        // Install apk extensions in runtime stage
        if (count($image->php_extensions) > 0) {
            $separated = \App\DockerfileHelpers\DockerfilePhpExtensions::separateExtensions($image->php_extensions);
            if (count($separated['apk']) > 0) {
                $commands[] = 'apk add --no-cache php' . $phpVersion . '-' . implode(' php' . $phpVersion . '-', $separated['apk']);
            }
        }

        // Remove wget if present
        $commands[] = 'apk del --no-cache wget || true';

        // ---------------- PHP ini adjustments ----------------
        if (! empty($image->max_file_size)) {
            $commands = array_merge($commands, DockerfileFileSize::getCommands($image->max_file_size, $iniFileLocation));
        }
        if (! empty($image->timeout)) {
            $commands = array_merge($commands, DockerfileTimeout::getCommands($image->timeout, $iniFileLocation));
        }

        // ---------------- Database runtime setup ----------------
        foreach ($image->databases as $db) {
            if ($db === 'oracle') {
                $runtimePackages = DockerfileDbOraSql::getRuntimePackages($phpVersion);
                $commands[] = 'apk add --no-cache '.implode(' ', $runtimePackages);
                $commands = array_merge($commands, DockerfileDbOraSql::getRuntimeCommands($image->tag));
            } elseif ($db === 'mssql') {
                $runtimePackages = DockerfileDbMsSql::getRuntimePackages($phpVersion);
                $commands[] = 'apk add --no-cache '.implode(' ', $runtimePackages);
                $commands = array_merge($commands, DockerfileDbMsSql::getRuntimeCommands($image->tag));
            } elseif ($db === 'mysql') {
                $runtimePackages = DockerfileDbMySql::getRuntimePackages($phpVersion);
                $commands[] = 'apk add --no-cache '.implode(' ', $runtimePackages);
                $commands = array_merge($commands, DockerfileDbMySql::getRuntimeCommands($image->tag));
            } elseif ($db === 'pgsql') {
                $runtimePackages = DockerfileDbPgSql::getRuntimePackages($phpVersion);
                $commands[] = 'apk add --no-cache '.implode(' ', $runtimePackages);
                $commands = array_merge($commands, DockerfileDbPgSql::getRuntimeCommands($image->tag));
            } elseif ($db === 'sqlite') {
                $runtimePackages = DockerfileDbSqlite::getRuntimePackages($phpVersion);
                $commands[] = 'apk add --no-cache '.implode(' ', $runtimePackages);
                $commands = array_merge($commands, DockerfileDbSqlite::getRuntimeCommands($image->tag));
            }
        }

        // ---------------- OS modules ----------------
        if (! empty($image->os_modules)) {
            $osModules = DockerfileOsModules::getRuntimePackages($image->os_modules);
            $commands[] = 'apk add --no-cache ' . implode(' ', $osModules);
        }

        // ---------------- Final cleanup ----------------
        $commands[] = 'rm -rf /var/cache/apk/* /usr/share/man/* /usr/share/doc/* /usr/share/info/* /tmp/* /var/tmp/*';

        return $this->formatConsolidatedRun($commands);
    }

    // ---------------------------------------------------------------------
    private function formatConsolidatedRun(array $commands): string
    {
        // Trim commands and remove empty ones
        $commands = array_map('trim', array_filter($commands));

        // Take all but the last command
        $allButLast = array_slice($commands, 0, -1);
        $last = end($commands);

        // Add " && \" to all but the last
        $lines = array_map(fn ($c) => "\t{$c} && \\", $allButLast);

        // Add last line without " && \"
        $lines[] = "\t{$last}";

        return "# Consolidated RUN layer for minimal image size\nRUN \\\n".implode("\n", $lines)."\n";
    }
}
